version: '2'
services:
    app:
        build: .
        restart: always
        environment:
            SYMFONY_ENV: prod
            VARNISH_CONFIG: /etc/varnish/default.vcl
            CACHE_SIZE: 512m
            VARNISHD_PARAMS: -p default_ttl=3600 -p default_grace=3600
            VARNISH_PORT: 80
        volumes: 
            - /home/uploads:/tmp/uploads
        links:
            - redis
        depends_on:
            - redis

    redis:
        image: redis:alpine
        restart: always

    balancer:
        image: dockercloud/haproxy:latest
        restart: always
        ports:
            - 8000:80
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        links:
            - app
        depends_on:
            - app
