services:
    persona.security.user_aware_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\UserAwareSubscriber'
        arguments:
            - '@persona.repository.orm.user_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.security.service_aware_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\ServiceAwareSubscriber'
        arguments:
            - '@persona.repository.orm.service_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.security.module_aware_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\ModuleAwareSubscriber'
        arguments:
            - '@persona.repository.orm.module_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.attendance.absent_reason_aware_subscriber:
        class: 'Persona\Hris\Attendance\Subscriber\AbsentReasonAwareSubscriber'
        arguments:
            - '@persona.repository.orm.absent_reason_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }