services:
    persona.security.user_aware_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\UserAwareSubscriber'
        arguments:
            - '@persona.repository.orm.user_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.security.service_aware_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\ServiceAwareSubscriber'
        arguments:
            - '@persona.repository.orm.service_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.security.module_aware_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\ModuleAwareSubscriber'
        arguments:
            - '@persona.repository.orm.module_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.attendance.absent_reason_aware_subscriber:
        class: 'Persona\Hris\Attendance\Subscriber\AbsentReasonAwareSubscriber'
        arguments:
            - '@persona.repository.orm.absent_reason_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.attendance.shiftment_subscriber:
        class: 'Persona\Hris\Attendance\Subscriber\ShiftmentAwareSubscriber'
        arguments:
            - '@persona.repository.orm.shiftment_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.employee.employee_aware_subscriber:
        class: 'Persona\Hris\Employee\Subscriber\EmployeeAwareSubscriber'
        arguments:
            - '@persona.repository.orm.employee_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.share.province_subscriber:
        class: 'Persona\Hris\Share\Subscriber\ProvinceAwareSubscriber'
        arguments:
            - '@persona.repository.orm.province_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.share.university_subscriber:
        class: 'Persona\Hris\Share\Subscriber\UniversityAwareSubscriber'
        arguments:
            - '@persona.repository.orm.university_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.share.education_title_subscriber:
        class: 'Persona\Hris\Share\Subscriber\EducationTitleAwareSubscriber'
        arguments:
            - '@persona.repository.orm.education_title_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.organization.company_subscriber:
        class: 'Persona\Hris\Organization\Subscriber\CompanyAwareSubscriber'
        arguments:
            - '@persona.repository.orm.company_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.organization.department_subscriber:
        class: 'Persona\Hris\Organization\Subscriber\DepartmentAwareSubscriber'
        arguments:
            - '@persona.repository.orm.department_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.organization.job_title_subscriber:
        class: 'Persona\Hris\Organization\Subscriber\JobTitleAwareSubscriber'
        arguments:
            - '@persona.repository.orm.job_title_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.performance.indicator_subscriber:
        class: 'Persona\Hris\Performance\Subscriber\IndicatorAwareSubscriber'
        arguments:
            - '@persona.repository.orm.indicator_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.course.course_subscriber:
        class: 'Persona\Hris\Course\Subscriber\CourseAwareSubscriber'
        arguments:
            - '@persona.repository.orm.course_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.salary.benefit_subscriber:
        class: 'Persona\Hris\Salary\Subscriber\BenefitAwareSubscriber'
        arguments:
            - '@persona.repository.orm.benefit_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }
