services:
    persona.security.user_aware_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\UserAwareSubscriber'
        arguments:
            - '@persona.repository.orm.user_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.security.service_aware_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\ServiceAwareSubscriber'
        arguments:
            - '@persona.repository.orm.service_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.security.module_aware_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\ModuleAwareSubscriber'
        arguments:
            - '@persona.repository.orm.module_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.attendance.absent_reason_aware_subscriber:
        class: 'Persona\Hris\Attendance\Subscriber\AbsentReasonAwareSubscriber'
        arguments:
            - '@persona.repository.orm.absent_reason_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.attendance.shiftment_subscriber:
        class: 'Persona\Hris\Attendance\Subscriber\ShiftmentAwareSubscriber'
        arguments:
            - '@persona.repository.orm.shiftment_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.employee.employee_aware_subscriber:
        class: 'Persona\Hris\Employee\Subscriber\EmployeeAwareSubscriber'
        arguments:
            - '@persona.repository.orm.employee_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.share.province_subscriber:
        class: 'Persona\Hris\Share\Subscriber\ProvinceAwareSubscriber'
        arguments:
            - '@persona.repository.orm.province_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }
