services:
    persona.logger.action_logger:
        class: 'Persona\Hris\Core\Logger\Subscriber\ActionLoggerSubscriber'
        arguments:
            - '@security.token_storage'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.client.check_api_key_generator_subscriber:
        class: 'Persona\Hris\Core\Client\Subscriber\ApiKeyGeneratorSubscriber'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.logger.activity_log_subscriber:
        class: 'Persona\Hris\Core\Logger\Subscriber\ActivityLogSubscriber'
        arguments:
            - '@persona.manager.manager_factory'
            - '@security.token_storage'
            - '@persona.repository.orm.client_repository'
            - '@persona.logger.exclude_logger_factory'
            - 'Persona\Hris\Entity\UserActivity'
        tags:
            - { name: 'doctrine.event_subscriber', connection: 'default' }
            - { name: 'kernel.event_listener', event: 'kernel.exception', method: 'onKernelException' }
            - { name: 'kernel.event_listener', event: 'kernel.terminate', method: 'onKernelTerminate' }
            
    persona.security.delete_user_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\DeleteUserSubscriber'
        arguments:
            - '@security.token_storage'
        tags:
            - { name: 'doctrine.event_subscriber' }
            
    persona.security.default_password_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\DefaultPasswordSubscriber'
        arguments:
            - '%persona.default_password%'
        tags:
            - { name: 'doctrine.event_subscriber' }
            
    persona.security.module_delete_checker_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\ModuleDeleteCheckerSubscriber'
        arguments:
            - '@persona.repository.orm.role_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }
            
    persona.upload.upload_subscriber:
        class: 'Persona\Hris\Core\Upload\UploadSubscriber'
        arguments:
            - '@persona.upload.uploader'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.security.remove_role_map_cache_subscriber:
        class: 'Persona\Hris\Core\Security\Subscriber\RemoveRoleMapCacheSubscriber'
        arguments:
            - '@persona.manager.manager_factory'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.allocation.contract_subscriber:
        class: 'Persona\Hris\Allocation\Subscriber\ContractSubscriber'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.allocation.job_allocation_subscriber:
        class: 'Persona\Hris\Allocation\Subscriber\JobAllocationSubscriber'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.allocation.mutation_subscriber:
        class: 'Persona\Hris\Allocation\Subscriber\MutationSubscriber'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.allocation.promotion_subscriber:
        class: 'Persona\Hris\Allocation\Subscriber\PromotionSubscriber'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.attendance.absent_subscriber:
        class: 'Persona\Hris\Attendance\Subscriber\AbsentSubscriber'
        arguments:
            - '@persona.repository.orm.employee_attendance_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.attendance.attendance_calculator_subscriber:
        class: 'Persona\Hris\Attendance\Subscriber\AttendanceCalculatorSubscriber'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.leave.employee_absent_subscriber:
        class: 'Persona\Hris\Leave\Subscriber\EmployeeAbsentSubscriber'
        arguments:
            - '@persona.repository.orm.employee_absent_repository'
            - 'Persona\Hris\Entity\LeaveBalance'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.performance.appraisal_period_subscriber:
        class: 'Persona\Hris\Performance\Subscriber\InactiveAppraisalPeriodSubscriber'
        arguments:
            - '@persona.repository.orm.appraisal_period_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.salary.payroll_period_subscriber:
        class: 'Persona\Hris\Salary\Subscriber\InactivePayrollPeriodSubscriber'
        arguments:
            - '@persona.repository.orm.payroll_period_repository'
            - '@persona.repository.orm.payroll_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.salary.prevent_reopen_payroll:
        class: 'Persona\Hris\Salary\Subscriber\PreventReopenPayrollSubscriber'
        arguments:
            - '@persona.repository.orm.payroll_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }

    persona.course.employee_course:
        class: 'Persona\Hris\Course\Subscriber\EmployeeCourseSubscriber'
        arguments:
            - '@persona.repository.orm.employee_course_repository'
        tags:
            - { name: 'doctrine.event_subscriber' }
