services:
    persona.repository.orm.client_repository:
        class: 'Persona\Hris\Repository\ORM\ClientRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Client'
            
    persona.repository.orm.module_repository:
        class: 'Persona\Hris\Repository\ORM\ModuleRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Module'
            
    persona.repository.orm.role_hierarchy_repository:
        class: 'Persona\Hris\Repository\ORM\RoleHierarchyRepository'
        arguments:
            - '@persona.repository.orm.role_repository'
            - '@security.token_storage'
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\User'

    persona.repository.orm.role_repository:
        class: 'Persona\Hris\Repository\ORM\RoleRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Role'
            
    persona.repository.orm.user_repository:
        class: 'Persona\Hris\Repository\ORM\UserRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\User'

    persona.repository.orm.service_repository:
        class: 'Persona\Hris\Repository\ORM\ServiceRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Service'

    persona.repository.orm.absent_reason_repository:
        class: 'Persona\Hris\Repository\ORM\AbsentReasonRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\AbsentReason'

    persona.repository.orm.employee_absent_repository:
        class: 'Persona\Hris\Repository\ORM\EmployeeAbsentRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\EmployeeAbsent'

    persona.repository.orm.employee_attendance_repository:
        class: 'Persona\Hris\Repository\ORM\EmployeeAttendanceRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Attendance'

    persona.repository.orm.holiday_repository:
        class: 'Persona\Hris\Repository\ORM\HolidayRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Holiday'

    persona.repository.orm.employee_overtime_repository:
        class: 'Persona\Hris\Repository\ORM\EmployeeOvertimeRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\EmployeeOvertime'

    persona.repository.orm.employee_shiftment_repository:
        class: 'Persona\Hris\Repository\ORM\EmployeeShiftmentRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\EmployeeShiftment'

    persona.repository.orm.employee_additional_benefit_repository:
        class: 'Persona\Hris\Repository\ORM\AdditionalBenefitRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\EmployeeAdditionalBenefit'

    persona.repository.orm.employee_benefit_repository:
        class: 'Persona\Hris\Repository\ORM\EmployeeBenefitRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\EmployeeBenefit'

    persona.repository.orm.employee_repository:
        class: 'Persona\Hris\Repository\ORM\EmployeeRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Employee'

    persona.repository.orm.employee_overtime_history_repository:
        class: 'Persona\Hris\Repository\ORM\EmployeeOvertimeHistoryRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\OvertimeHistory'

    persona.repository.orm.payroll_repository:
        class: 'Persona\Hris\Repository\ORM\PayrollRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Payroll'

    persona.repository.orm.appraisal_period_repository:
        class: 'Persona\Hris\Repository\ORM\AppraisalPeriodRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\AppraisalPeriod'

    persona.repository.orm.payroll_period_repository:
        class: 'Persona\Hris\Repository\ORM\PayrollPeriodRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\PayrollPeriod'

    persona.repository.orm.payroll_detail_repository:
        class: 'Persona\Hris\Repository\ORM\PayrollDetailRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\PayrollDetail'

    persona.repository.orm.tax_history_repository:
        class: 'Persona\Hris\Repository\ORM\TaxHistoryRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\TaxHistory'

    persona.repository.orm.employee_course_repository:
        class: 'Persona\Hris\Repository\ORM\EmployeeCourseRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\EmployeeCourse'

    persona.repository.orm.shiftment_repository:
        class: 'Persona\Hris\Repository\ORM\ShiftmentRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Shiftment'

    persona.repository.orm.province_repository:
        class: 'Persona\Hris\Repository\ORM\ProvinceRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Province'

    persona.repository.orm.company_repository:
        class: 'Persona\Hris\Repository\ORM\CompanyRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Company'

    persona.repository.orm.department_repository:
        class: 'Persona\Hris\Repository\ORM\DepartmentRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Department'

    persona.repository.orm.indicator_repository:
        class: 'Persona\Hris\Repository\ORM\IndicatorRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Indicator'

    persona.repository.orm.university_repository:
        class: 'Persona\Hris\Repository\ORM\UniversityRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\University'

    persona.repository.orm.course_repository:
        class: 'Persona\Hris\Repository\ORM\CourseRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Course'

    persona.repository.orm.job_title_repository:
        class: 'Persona\Hris\Repository\ORM\JobTitleRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\JobTitle'

    persona.repository.orm.education_title_repository:
        class: 'Persona\Hris\Repository\ORM\EducationTitleRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\EducationTitle'

    persona.repository.orm.benefit_repository:
        class: 'Persona\Hris\Repository\ORM\BenefitRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Benefit'

    persona.repository.orm.leave_repository:
        class: 'Persona\Hris\Repository\ORM\LeaveRepository'
        arguments:
            - '@persona.manager.manager_factory'
            - 'Persona\Hris\Entity\Leave'
